apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-api
  namespace: forensic-tools
  labels:
    app: asr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-api
  template:
    metadata:
      labels:
        app: asr-api
    spec:
      containers:
        - name: asr-api
          image: "pbusenius/asr-api:0.1.1"
          ports:
            - containerPort: 9000
          env:
            - name: ASR_MODEL
              value: "base"
            - name: ASR_ENGINE
              value: "faster_whisper"
            - name: OTEL_ENABLED
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "asr-api"
            - name: OTEL_PROMETHEUS_METRICS_PATH
              value: "/metrics"
            # Optional: If you want to push metrics via OTLP instead of scraping
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "http://prometheus-server.monitoring.svc.cluster.local:80"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"

